# Generated by Django 5.0 on 2024-12-08 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('compactadores', 'Compactadores de Solo'), ('placas', 'Placas Vibratórias'), ('cortadoras', 'Cortadoras'), ('bombas', 'Bombas'), ('vibradores', 'Vibradores'), ('motores', 'Motores'), ('outros', 'Outros')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specs', models.JSONField(default=dict, help_text='Dynamic specifications like {"potência": "2000W"}')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('catalog', 'Catalog')], max_length=20)),
                ('nextcloud_link', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
        ),
    ]
